version: '3.8'
services:
  app:
    container_name: mymt5
    image: mymt5
    restart: unless-stopped
    ports:
      - '5900:5900'
      - '15555:15555'
      - '15556:15556'
      - '15557:15557'
      - '15558:15558'
    volumes:
      - mymt5:/data
      - ./shared:/shared
 
      
volumes:
  mymt5: {}